version: "3.8"

services:
    postgres:
        image: postgres:18
        container_name: t3-cat-inventory-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: t3-cat-inventory
        volumes:
            - data_postgres:/var/lib/postgresql/18/docker

volumes:
    data_postgres: